[tool.dependencies]
accelerate = "1.0.1"
aiofiles = "24.1.0"
aiogram = "3.19.0"
aiohappyeyeballs = "2.4.3"
aiohttp = "3.10.10"
aiosignal = "1.3.1"
albucore = "0.0.21"
albumentations = "1.4.22"
alembic = "1.14.0"
annotated-types = "0.7.0"
anyio = "4.6.0"
argcomplete = "3.6.0"
argon2-cffi = "23.1.0"
argon2-cffi-bindings = "21.2.0"
arrow = "1.3.0"
asteroid = "0.7.0"
asteroid-filterbanks = "0.4.0"
asttokens = "2.4.1"
async-lru = "2.0.4"
async-timeout = "4.0.3"
attrs = "24.2.0"
Automat = "20.2.0"
babel = "2.16.0"
backcall = "0.2.0"
bcrypt = "3.2.0"
beautifulsoup4 = "4.12.3"
bleach = "6.1.0"
blinker = "1.9.0"
bokeh = "3.6.2"
build = "1.2.2.post1"
cached-property = "2.0.1"
cachetools = "5.5.0"
certifi = "2024.8.30"
cffi = "1.17.1"
chardet = "4.0.0"
charset-normalizer = "3.3.2"
click = "8.1.7"
cloud-init = "24.4.1"
cloudpickle = "3.1.0"
colorama = "0.4.6"
comm = "0.2.2"
command-not-found = "0.3"
configobj = "5.0.6"
constantly = "15.1.0"
contourpy = "1.3.0"
cryptography = "3.4.8"
cvxopt = "1.3.2"
cycler = "0.12.1"
databricks-sdk = "0.37.0"
datasets = "3.0.2"
dbus-python = "1.2.18"
debugpy = "1.8.6"
decorator = "4.4.2"
deepspeed = "0.15.3"
defusedxml = "0.7.1"
Deprecated = "1.2.14"
dill = "0.3.8"
distro = "1.7.0"
distro-info = "1.1+ubuntu0.2"
docker = "7.1.0"
docker-compose = "1.29.2"
dockerpty = "0.4.1"
docopt = "0.6.2"
docutils = "0.21.2"
einops = "0.8.0"
eval_type_backport = "0.2.0"
exceptiongroup = "1.2.2"
executing = "2.1.0"
fastjsonschema = "2.20.0"
filelock = "3.16.1"
Flask = "3.1.0"
fonttools = "4.53.1"
fqdn = "1.5.1"
frozenlist = "1.5.0"
fsspec = "2024.9.0"
future = "1.0.0"
gensim = "4.3.3"
gitdb = "4.0.11"
GitPython = "3.1.43"
google-auth = "2.36.0"
graphene = "3.4.3"
graphql-core = "3.2.5"
graphql-relay = "3.2.0"
greenlet = "3.1.1"
gunicorn = "23.0.0"
h11 = "0.14.0"
hjson = "3.1.0"
httpcore = "1.0.5"
httplib2 = "0.20.2"
httpx = "0.27.2"
huggingface-hub = "0.26.1"
hyperlink = "21.0.0"
id = "1.5.0"
idna = "3.10"
imageio = "2.35.1"
imageio-ffmpeg = "0.5.1"
imbalanced-learn = "0.13.0"
imblearn = "0.0"
importlib_metadata = "8.5.0"
incremental = "21.3.0"
iniconfig = "2.0.0"
ipykernel = "6.29.5"
ipython = "8.12.3"
ipywidgets = "8.1.5"
isoduration = "20.11.0"
itsdangerous = "2.2.0"
jedi = "0.19.1"
jeepney = "0.7.1"
Jinja2 = "3.1.4"
joblib = "1.4.2"
json5 = "0.9.25"
jsonpatch = "1.32"
jsonpointer = "3.0.0"
jsonschema = "4.23.0"
jsonschema-specifications = "2023.12.1"
julius = "0.2.7"
jupyter = "1.1.1"
jupyter-console = "6.6.3"
jupyter-events = "0.10.0"
jupyter-lsp = "2.2.5"
jupyter_client = "8.6.3"
jupyter_core = "5.7.2"
jupyter_server = "2.14.2"
jupyter_server_terminals = "0.5.3"
jupyterlab = "4.2.5"
jupyterlab_pygments = "0.3.0"
jupyterlab_server = "2.27.3"
jupyterlab_widgets = "3.0.13"
keyring = "23.5.0"
kiwisolver = "1.4.7"
launchpadlib = "1.10.16"
"lazr.restfulclient" = "0.14.4"
"lazr.uri" = "1.0.6"
lazy_loader = "0.4"
lightning-utilities = "0.11.8"
magic-filter = "1.0.12"
Mako = "1.3.6"
Markdown = "3.7"
markdown-it-py = "3.0.0"
MarkupSafe = "2.1.5"
matplotlib = "3.9.2"
matplotlib-inline = "0.1.7"
mdurl = "0.1.2"
mir-eval = "0.7"
mistune = "3.0.2"
mlflow = "2.17.2"
mlflow-skinny = "2.17.2"
mock = "5.1.0"
more-itertools = "8.10.0"
moviepy = "1.0.3"
mpmath = "1.3.0"
msgpack = "1.1.0"
multidict = "6.1.0"
multiprocess = "0.70.16"
nbclient = "0.10.0"
nbconvert = "7.16.4"
nbformat = "5.10.4"
nest-asyncio = "1.6.0"
netifaces = "0.11.0"
networkx = "3.3"
newawersometexcellentwondertexdragonphoenixninjaunicorntexasrangerlatexmasterpiecegenerator = "0.1.0"
nh3 = "0.2.21"
ninja = "1.11.1.1"
nltk = "3.9.1"
notebook = "7.2.2"
notebook_shim = "0.2.4"
numpy = "1.26.4"
nvidia-cublas-cu12 = "12.4.5.8"
nvidia-cuda-cupti-cu12 = "12.4.127"
nvidia-cuda-nvrtc-cu12 = "12.4.127"
nvidia-cuda-runtime-cu12 = "12.4.127"
nvidia-cudnn-cu12 = "9.1.0.70"
nvidia-cufft-cu12 = "11.2.1.3"
nvidia-curand-cu12 = "10.3.5.147"
nvidia-cusolver-cu12 = "11.6.1.9"
nvidia-cusparse-cu12 = "12.3.1.170"
nvidia-nccl-cu12 = "2.21.5"
nvidia-nvjitlink-cu12 = "12.4.127"
nvidia-nvtx-cu12 = "12.4.127"
oauthlib = "3.2.0"
opencv-python = "4.10.0.84"
opencv-python-headless = "4.10.0.84"
opentelemetry-api = "1.28.1"
opentelemetry-sdk = "1.28.1"
opentelemetry-semantic-conventions = "0.49b1"
overrides = "7.7.0"
packaging = "24.2"
pandas = "2.2.3"
pandocfilters = "1.5.1"
parso = "0.8.4"
pb-bss-eval = "0.0.2"
pesq = "0.0.4"
pexpect = "4.9.0"
pickleshare = "0.7.5"
pigar = "2.1.7"
pillow = "10.4.0"
pipreqs = "0.5.0"
pipx = "1.7.1"
platformdirs = "4.3.6"
pluggy = "1.5.0"
proglog = "0.1.10"
prometheus_client = "0.21.0"
prompt_toolkit = "3.0.48"
propcache = "0.2.0"
protobuf = "5.28.3"
psutil = "6.0.0"
ptyprocess = "0.7.0"
pure_eval = "0.2.3"
py-cpuinfo = "9.0.0"
pyarrow = "17.0.0"
pyasn1 = "0.6.1"
pyasn1_modules = "0.4.1"
pycairo = "1.20.1"
pycparser = "2.22"
pycurl = "7.44.1"
pydantic = "2.9.2"
pydantic_core = "2.23.4"
Pygments = "2.18.0"
PyGObject = "3.42.1"
PyHamcrest = "2.0.2"
PyJWT = "2.3.0"
pyOpenSSL = "21.0.0"
pyparsing = "3.1.4"
pyproject_hooks = "1.2.0"
pyrsistent = "0.18.1"
pyserial = "3.5"
pystoi = "0.4.1"
pytest = "8.3.2"
python-apt = "2.4.0+ubuntu4"
python-dateutil = "2.9.0.post0"
python-dotenv = "1.0.1"
python-json-logger = "2.0.7"
pytorch-lightning = "2.4.0"
pytorch-ranger = "0.1.1"
pytz = "2024.2"
PyYAML = "5.4.1"
pyzmq = "26.2.0"
readme_renderer = "44.0"
referencing = "0.35.1"
regex = "2024.9.11"
requests = "2.32.3"
requests-toolbelt = "1.0.0"
rfc3339-validator = "0.1.4"
rfc3986 = "2.0.0"
rfc3986-validator = "0.1.1"
rich = "13.9.4"
rpds-py = "0.20.0"
rsa = "4.9"
safetensors = "0.4.5"
scikit-image = "0.24.0"
scikit-learn = "1.5.1"
scipy = "1.13.1"
seaborn = "0.13.2"
SecretStorage = "3.3.1"
Send2Trash = "1.8.3"
sentencepiece = "0.2.0"
service-identity = "18.1.0"
simsimd = "6.2.1"
six = "1.16.0"
sklearn-compat = "0.1.3"
smart-open = "7.1.0"
smmap = "5.0.1"
sniffio = "1.3.1"
soundfile = "0.12.1"
soupsieve = "2.6"
SQLAlchemy = "2.0.36"
sqlparse = "0.5.2"
stack-data = "0.6.3"
stringzilla = "3.11.1"
subword-nmt = "0.3.8"
sympy = "1.13.1"
systemd-python = "234"
terminado = "0.18.1"
texcellent-wondertex-dragon-phoenix-ninja-unicorn-texas-ranger-latex-masterpiece-generator = "0.1.0"
texcellent_wondertex_latex_generator = "0.1.0"
texcellentlatexgenerator = "0.4.0"
texttable = "1.6.4"
threadpoolctl = "3.5.0"
tifffile = "2024.8.30"
tinycss2 = "1.3.0"
tokenizers = "0.20.1"
toml = "0.10.2"
tomli = "2.0.1"
torch = "2.5.0"
torch-optimizer = "0.1.0"
torch-stoi = "0.2.3"
torchaudio = "2.5.0"
torchmetrics = "0.11.4"
torchvision = "0.20.0"
tornado = "6.4.1"
tqdm = "4.66.5"
traitlets = "5.14.3"
transformers = "4.46.2"
triton = "3.1.0"
twine = "6.1.0"
Twisted = "22.1.0"
types-python-dateutil = "2.9.0.20240906"
typing_extensions = "4.12.2"
tzdata = "2024.2"
ubuntu-pro-client = "8001"
ufw = "0.36.1"
unattended-upgrades = "0.1"
uri-template = "1.3.0"
urllib3 = "2.2.3"
userpath = "1.9.2"
uv = "0.6.6"
wadllib = "1.3.6"
wcwidth = "0.2.13"
webcolors = "24.8.0"
webencodings = "0.5.1"
websocket-client = "1.8.0"
Werkzeug = "3.1.3"
widgetsnbextension = "4.0.13"
wrapt = "1.16.0"
xxhash = "3.5.0"
xyzservices = "2024.9.0"
yarg = "0.1.9"
yarl = "1.16.0"
zipp = "3.21.0"
"zope.interface" = "5.4.0"
